### ISSUE TITLE
Documentation tracking issue!

### ISSUE THREAD

**Issue by josephsdavid** [JuliaAI/MLJGLMInterface.jl#25]
- [x] Add skeleton docstrings to fill out
- [x] Document internal helpers
- [x] Document linear regression function and structs
- [x] Document binary regression functions and structs
- [x] Document count regression functions and structs

**Comment by josephsdavid** [comment]
A few questions:

A few questions:

How do I document:
```julia
function MMI.predict_mean(model::LinearBinaryClassifier, (fitresult, _), Xnew)
```
and
```julia
function MMI.predict(model::LinearBinaryClassifier, (fitresult, decode), Xnew)
```
?

Is there a reason we preemptively unpack this iterable instead of having one named parameter the function takes in and then unpacking it internally? 

Secondarily, at what point do we go from:

```julia
"""
    function foo(X, y, z)

blurb
"""
``` 
to

```julia
"""
    function foo(X, y, z)

blurb

# Arguments
- `X`:
- ....
"""
```

I am relatively new to julia and this has been bothering me for a bit :)

**Comment by ablaom** [comment]
> A few questions:
> 
> A few questions:
> 
> How do I document:
> 
> ```julia
> function MMI.predict_mean(model::LinearBinaryClassifier, (fitresult, _), Xnew)
> ```

You don't. See comments at #26 

> and
> 
> ```julia
> function MMI.predict(model::LinearBinaryClassifier, (fitresult, decode), Xnew)
> ```
> 
> ?
> 
> Is there a reason we preemptively unpack this iterable instead of having one named parameter the function takes in and then unpacking it internally?

I guess this is mainly a style point. I doubt it will compile any differently either way. 

> Secondarily, at what point do we go from:
> 
> ```julia
> """
>     function foo(X, y, z)
> 
> blurb
> """
> ```
> 
> to
> 
> ```julia
> """
>     function foo(X, y, z)
> 
> blurb
> 
> # Arguments
> - `X`:
> - ....
> """
> ```
> 
> I am relatively new to julia and this has been bothering me for a bit :)

Yeah good question. Personally, I usually unpack the options when they no longer fit on one line of the doc-header. There is a style guide that we say we adopt: https://github.com/invenia/BlueStyle Maybe it says there. 

In the case of the current documentation roll-out though, this point is mute. You always unpack the options (hyper-parameters) in a model doc-string

**Comment by josephsdavid** [comment]
> Yeah good question. Personally, I usually unpack the options when they no longer fit on one line of the doc-header. There is a style guide that we say we adopt: https://github.com/invenia/BlueStyle Maybe it says there.

Ah this is super helpful! I will read through this more closely!
